DROP SCHEMA PROJECTDB;

CREATE DATABASE PROJECTDB;

use PROJECTDB;

CREATE TABLE MEDIA_SERVERS (
	Server_id INT NOT NULL,
	IP INT UNSIGNED NOT NULL,
	Port INT NOT NULL,
	CONSTRAINT MS_PK PRIMARY KEY(Server_id)
);

CREATE TABLE TV_MOVIES (
	TV_Movie_id INT NOT NULL,
	TV_Movie_name VARCHAR(100) NOT NULL,
	CONSTRAINT TV_MOVIES_PK PRIMARY KEY(TV_Movie_id)
);

CREATE TABLE CATEGORIES (
	Category_id INT NOT NULL,
	Category_name VARCHAR(50) NOT NULL,
	CONSTRAINT CAT_PK PRIMARY KEY(Category_id)
);

CREATE TABLE AVAILABLE_TV_MOVIES (
	TV_Movie_id INT NOT NULL,
	Server_id INT NOT NULL,
	CONSTRAINT AVAIL_TVMV_PK PRIMARY KEY(TV_Movie_id, Server_id),
	CONSTRAINT AVAIL_TVMV_TVMOVIE_FK FOREIGN KEY(TV_Movie_id) REFERENCES TV_MOVIES(TV_Movie_id),
	CONSTRAINT AVAIL_TVMV_SERVER_FK FOREIGN KEY(Server_id) REFERENCES MEDIA_SERVERS(Server_id)
);

CREATE TABLE TV_MOVIE_CATEGORY (
	TV_Movie_id INT NOT NULL,
	Category_id INT NOT NULL,
	CONSTRAINT TVMV_CAT_PK PRIMARY KEY(TV_Movie_id, Category_id),
	CONSTRAINT TVMV_CAT_MOVIE_FK FOREIGN KEY(TV_Movie_id) REFERENCES TV_MOVIES(TV_Movie_id),
	CONSTRAINT TVMV_CAT_CATEGORY_FK FOREIGN KEY(Category_id) REFERENCES CATEGORIES(Category_id)
);
